### ISSUE TITLE
What if there are multi labels between two objects?

### ISSUE THREAD

**Issue by PhyllisH** [SiyuanQi/gpnn#9]
Thanks for releasing the code.
If there are different kinds of relationships between two objects, how should they be expressed in the graph. In my understanding, the graph that you bulit can only have one edge between two nodes.

I'll appreciate a lot if you can give me some advice. Thanks.

**Comment by ZHUXUHAN** [comment]
There should be only one relationship between each person and a single object in the annotations in the dataset. Can you give an example to illustrate your problem?

**Comment by PhyllisH** [comment]
Yep. But in some other tasks, there may be two annotated relationship between human and object, such as 'person has bag' and 'person carry bag'.

**Comment by SiyuanQi-zz** [comment]
One way to do that can be applying a readout function to edge features, which could be a multi-label output.

**Comment by karenyun** [comment]
Hi @SiyuanQi ，
I am still confused about the definition of the complete HOI graph. 
1) Since in the HICO-DET dataset where an object can have many interaction labels. While in your paper which states that every node has only 'an output state y'?
2) Is the complete HOI graph defined on the whole dataset, I mean that the number of the nodes in G does not change, though one input image may have a small number of objects?

I appreciate a lot if you can give me some advice. Thanks very much!
